resilience4j:
  retry:
    instances:
      currencyExchangeRetry:
        max-attempts: 3
        wait-duration: 10000ms
        retry-exceptions:
          - feign.FeignException$ServiceUnavailable
          - java.io.IOException
        ignore-exceptions:
          - com.suraj.currency.currency_conversion_service.exception.CurrencyPairNotFoundException
