spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/surajhanvate07/currency-conversion-config.git
          username: surajhanvate07
          password:
          default-label: main

server:
  port: 8888